############################################################
# Dockerfile to build Czecoind container images
# Based on Ubuntu
############################################################

FROM ubuntu:14.04
MAINTAINER laudney

RUN apt-get update
RUN apt-get install -y git make g++ python-leveldb libboost-all-dev libssl-dev libdb++-dev pkg-config libminiupnpc-dev wget xz-utils
RUN apt-get clean

RUN adduser Czecoin --disabled-password
USER Czecoin

WORKDIR /home/Czecoin
RUN mkdir bin src
RUN echo PATH=\"\$HOME/bin:\$PATH\" >> .bash_profile

WORKDIR /home/Czecoin/src
RUN git clone https://github.com/Czecoin-project/Czecoin.git

WORKDIR	/home/Czecoin/src/Czecoin/src
RUN make -f makefile.unix
RUN strip Czecoind
RUN cp -f Czecoind /home/Czecoin/bin/
RUN make -f makefile.unix clean

WORKDIR	 /home/Czecoin
RUN mkdir .Czecoin
RUN cp -f src/Czecoin/contrib/docker/Czecoin.conf .Czecoin/

WORKDIR /home/Czecoin/.Czecoin
RUN wget -q https://github.com/Czecoin-project/Czecoin/releases/download/v1.3.1.2/bootstrap.dat.xz

ENV HOME /home/Czecoin
EXPOSE 8332
USER Czecoin
